---
- name: Manage root login
  hosts: all
  become: true

  vars:
    sshd:
    # root login and password login is enabled only from a particular subnet
      PermitRootLogin: false
      PasswordAuthentication: false
      Match:
        - Condition: "Address 172.27.0.0/16"
          PermitRootLogin: true
          PasswordAuthentication: true

  roles:
    - role: redhat.rhel_system_roles.sshd
    